apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-httpserver
  name: go-httpservice
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: go-httpserver
